import Nav from '@/components/nav/Nav'
import './globals.css'
import {sg} from './fonts.js'
import { ThemeProvider } from '@/context/ThemeContext'
import Footer from '@/components/footer/Footer'





export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sg.className}>
        <ThemeProvider>
          <Nav/>
          {children}
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  )
}
