import Nav from '@/components/nav/Nav'
import './globals.css'
import { Space_Grotesk } from 'next/font/google'
import { ThemeProvider } from '@/context/ThemeContext'
import Footer from '@/components/footer/Footer'



const sg = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sg.className}>
        <ThemeProvider>
          <Nav />
          {children}
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  )
}
