import './globals.css'
import { Space_Grotesk } from 'next/font/google'

const sg = Space_Grotesk({ 
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sg.className}>{children}</body>
    </html>
  )
}
